-- MySQL Script generated by MySQL Workbench
-- Sun Sep  8 15:59:43 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Projektni_zadatak
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Projektni_zadatak
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Projektni_zadatak` DEFAULT CHARACTER SET utf8 ;
USE `Projektni_zadatak` ;

-- -----------------------------------------------------
-- Table `AUTOR`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AUTOR` (
  `idAutor` INT NOT NULL AUTO_INCREMENT,
  `Ime` VARCHAR(25) NOT NULL,
  `Prezime` VARCHAR(30) NOT NULL,
  `brojTelefona` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`idAutor`),
  UNIQUE INDEX `idAutor_UNIQUE` (`idAutor` ASC) VISIBLE,
  UNIQUE INDEX `brojTelefona_UNIQUE` (`brojTelefona` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DOBAVLJAC`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DOBAVLJAC` (
  `idDobavljac` INT NOT NULL AUTO_INCREMENT,
  `Adresa` VARCHAR(50) NOT NULL,
  `Ime` VARCHAR(45) NOT NULL,
  `brojTelefona` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`idDobavljac`),
  UNIQUE INDEX `idDOBAVLJAČ_UNIQUE` (`idDobavljac` ASC) VISIBLE,
  UNIQUE INDEX `brojTelefona_UNIQUE` (`brojTelefona` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `INDIVIDUALAC`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `INDIVIDUALAC` (
  `Ime` VARCHAR(25) NOT NULL,
  `Prezime` VARCHAR(30) NOT NULL,
  `idKlijent` INT NOT NULL,
  PRIMARY KEY (`idKlijent`),
  INDEX `fk_Indiviualac_Klijent1_idx` (`idKlijent` ASC) VISIBLE,
  CONSTRAINT `fk_Indiviualac_Klijent1`
    FOREIGN KEY (`idKlijent`)
    REFERENCES `KLIJENT` (`idKlijent`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `INVENTAR`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `INVENTAR` (
  `idPoslovnica` INT NOT NULL,
  `Kolicina` INT NOT NULL,
  `idProizvod` INT NOT NULL,
  PRIMARY KEY (`idPoslovnica`, `idProizvod`),
  INDEX `fk_INVENTAR_POSLOVNICA1_idx` (`idPoslovnica` ASC) VISIBLE,
  INDEX `fk_INVENTAR_PROIZVOD1_idx` (`idProizvod` ASC) VISIBLE,
  CONSTRAINT `fk_INVENTAR_POSLOVNICA1`
    FOREIGN KEY (`idPoslovnica`)
    REFERENCES `POSLOVNICA` (`idPoslovnica`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_INVENTAR_PROIZVOD1`
    FOREIGN KEY (`idProizvod`)
    REFERENCES `PROIZVOD` (`idProizvod`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `KATEGORIJA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `KATEGORIJA` (
  `idKategorija` INT NOT NULL AUTO_INCREMENT,
  `Naziv` VARCHAR(60) NOT NULL,
  PRIMARY KEY (`idKategorija`),
  UNIQUE INDEX `idKATEGORIJA_UNIQUE` (`idKategorija` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `KLIJENT`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `KLIJENT` (
  `idKlijent` INT NOT NULL AUTO_INCREMENT,
  `Adresa` VARCHAR(50) NOT NULL,
  `brojTelefona` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`idKlijent`),
  UNIQUE INDEX `idKlijent_UNIQUE` (`idKlijent` ASC) VISIBLE,
  UNIQUE INDEX `brojTelefona_UNIQUE` (`brojTelefona` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `NABAVKA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `NABAVKA` (
  `idNabavka` INT NOT NULL AUTO_INCREMENT,
  `DatumKreiranja` DATE NOT NULL,
  `idDobavljac` INT NOT NULL,
  `idZaposleni` INT NOT NULL,
  `idPoslovnica` INT NOT NULL,
  PRIMARY KEY (`idNabavka`),
  INDEX `fk_PORUDZBINA_DOBAVLJAČ1_idx` (`idDobavljac` ASC) VISIBLE,
  INDEX `fk_NABAVKA_ZAPOSLENI1_idx` (`idZaposleni` ASC) VISIBLE,
  INDEX `fk_NABAVKA_POSLOVNICA1_idx` (`idPoslovnica` ASC) VISIBLE,
  UNIQUE INDEX `idNABAVKA_UNIQUE` (`idNabavka` ASC) VISIBLE,
  CONSTRAINT `fk_NABAVKA_DOBAVLJAČ1`
    FOREIGN KEY (`idDobavljac`)
    REFERENCES `DOBAVLJAC` (`idDobavljac`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_NABAVKA_ZAPOSLENI1`
    FOREIGN KEY (`idZaposleni`)
    REFERENCES `ZAPOSLENI` (`idZaposleni`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_NABAVKA_POSLOVNICA1`
    FOREIGN KEY (`idPoslovnica`)
    REFERENCES `POSLOVNICA` (`idPoslovnica`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `NABAVKA_STAVKA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `NABAVKA_STAVKA` (
  `idNabavka` INT NOT NULL,
  `idProizvod` INT NOT NULL,
  `Kolicina` INT NOT NULL,
  `NabavnaCijena` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`idNabavka`, `idProizvod`),
  INDEX `fk_PORUDZBINA_STAVKA_PORUDZBINA1_idx` (`idNabavka` ASC) VISIBLE,
  INDEX `fk_NABAVKA_STAVKA_PROIZVOD1_idx` (`idProizvod` ASC) VISIBLE,
  CONSTRAINT `fk_PORUDZBINA_STAVKA_PORUDZBINA1`
    FOREIGN KEY (`idNabavka`)
    REFERENCES `NABAVKA` (`idNabavka`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_NABAVKA_STAVKA_PROIZVOD1`
    FOREIGN KEY (`idProizvod`)
    REFERENCES `PROIZVOD` (`idProizvod`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `NARUDZBA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `NARUDZBA` (
  `idNarudzba` INT NOT NULL AUTO_INCREMENT,
  `Vrijeme` DATETIME NOT NULL,
  `idKlijent` INT NOT NULL,
  `idRacun` INT NOT NULL,
  `idStatusNarudzbe` INT NOT NULL,
  PRIMARY KEY (`idNarudzba`),
  INDEX `fk_NARUDZBA_KLIJENT1_idx` (`idKlijent` ASC) VISIBLE,
  INDEX `fk_NARUDZBA_RACUN1_idx` (`idRacun` ASC) VISIBLE,
  UNIQUE INDEX `idNARUDZBA_UNIQUE` (`idNarudzba` ASC) VISIBLE,
  INDEX `fk_NARUDZBA_STATUS_NARUDZBE1_idx` (`idStatusNarudzbe` ASC) VISIBLE,
  CONSTRAINT `fk_NARUDZBA_KLIJENT1`
    FOREIGN KEY (`idKlijent`)
    REFERENCES `KLIJENT` (`idKlijent`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_NARUDZBA_RACUN1`
    FOREIGN KEY (`idRacun`)
    REFERENCES `RACUN` (`idRacun`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_NARUDZBA_STATUS_NARUDZBE1`
    FOREIGN KEY (`idStatusNarudzbe`)
    REFERENCES `STATUS_NARUDZBE` (`idStatusNarudzbe`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `NARUDZBA_STAVKA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `NARUDZBA_STAVKA` (
  `Kolicina` INT NOT NULL,
  `Cijena` DECIMAL NOT NULL,
  `idProizvod` INT NOT NULL,
  `idNarudzba` INT NOT NULL,
  PRIMARY KEY (`idProizvod`, `idNarudzba`),
  INDEX `fk_NARUDZBA_STAVKA_PROIZVOD1_idx` (`idProizvod` ASC) VISIBLE,
  INDEX `fk_NARUDZBA_STAVKA_NARUDZBA1_idx` (`idNarudzba` ASC) VISIBLE,
  CONSTRAINT `fk_NARUDZBA_STAVKA_PROIZVOD1`
    FOREIGN KEY (`idProizvod`)
    REFERENCES `PROIZVOD` (`idProizvod`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_NARUDZBA_STAVKA_NARUDZBA1`
    FOREIGN KEY (`idNarudzba`)
    REFERENCES `NARUDZBA` (`idNarudzba`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `POSLOVNICA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `POSLOVNICA` (
  `idPoslovnica` INT NOT NULL AUTO_INCREMENT,
  `Adresa` VARCHAR(50) NOT NULL,
  `brojTelefona` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`idPoslovnica`),
  UNIQUE INDEX `idPOSLOVNICA_UNIQUE` (`idPoslovnica` ASC) VISIBLE,
  UNIQUE INDEX `brojTelefona_UNIQUE` (`brojTelefona` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PROIZVOD`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PROIZVOD` (
  `idProizvod` INT NOT NULL AUTO_INCREMENT,
  `idKategorija` INT NOT NULL,
  `Ime` VARCHAR(45) NOT NULL,
  `Cijena` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`idProizvod`),
  INDEX `fk_PROIZVOD_KATEGORIJA1_idx` (`idKategorija` ASC) VISIBLE,
  UNIQUE INDEX `idPROIZVOD_UNIQUE` (`idProizvod` ASC) VISIBLE,
  CONSTRAINT `fk_PROIZVOD_KATEGORIJA1`
    FOREIGN KEY (`idKategorija`)
    REFERENCES `KATEGORIJA` (`idKategorija`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RACUN`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RACUN` (
  `idRacun` INT NOT NULL AUTO_INCREMENT,
  `Vrijeme` DATETIME NOT NULL,
  `idZaposleni` INT NOT NULL,
  PRIMARY KEY (`idRacun`),
  INDEX `fk_RACUN_ZAPOSLENI1_idx` (`idZaposleni` ASC) VISIBLE,
  UNIQUE INDEX `idRACUN_UNIQUE` (`idRacun` ASC) VISIBLE,
  CONSTRAINT `fk_RACUN_ZAPOSLENI1`
    FOREIGN KEY (`idZaposleni`)
    REFERENCES `ZAPOSLENI` (`idZaposleni`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RACUN_STAVKA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RACUN_STAVKA` (
  `idRacun` INT NOT NULL,
  `idProizvod` INT NOT NULL,
  `Kolicina` INT NOT NULL,
  `Cijena` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`idRacun`, `idProizvod`),
  INDEX `fk_RACUN_STAVKA_PROIZVOD1_idx` (`idProizvod` ASC) VISIBLE,
  UNIQUE INDEX `idRACUN_UNIQUE` (`idRacun` ASC) VISIBLE,
  CONSTRAINT `fk_RACUN_STAVKA_RACUN1`
    FOREIGN KEY (`idRacun`)
    REFERENCES `RACUN` (`idRacun`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_RACUN_STAVKA_PROIZVOD1`
    FOREIGN KEY (`idProizvod`)
    REFERENCES `PROIZVOD` (`idProizvod`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SERTIFIKAT`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SERTIFIKAT` (
  `Serijski_broj` INT NOT NULL AUTO_INCREMENT,
  `Datum` DATE NOT NULL,
  `idKlijent` INT NOT NULL,
  `idPoslovnica` INT NOT NULL,
  `idSlika` INT NOT NULL,
  `idZaposleni` INT NOT NULL,
  PRIMARY KEY (`Serijski_broj`),
  INDEX `fk_SERTIFIKAT_KLIJENT1_idx` (`idKlijent` ASC) VISIBLE,
  INDEX `fk_SERTIFIKAT_POSLOVNICA1_idx` (`idPoslovnica` ASC) VISIBLE,
  UNIQUE INDEX `Serijski_broj_UNIQUE` (`Serijski_broj` ASC) VISIBLE,
  INDEX `fk_SERTIFIKAT_SLIKA1_idx` (`idSlika` ASC) VISIBLE,
  INDEX `fk_SERTIFIKAT_ZAPOSLENI1_idx` (`idZaposleni` ASC) VISIBLE,
  CONSTRAINT `fk_SERTIFIKAT_KLIJENT1`
    FOREIGN KEY (`idKlijent`)
    REFERENCES `KLIJENT` (`idKlijent`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_SERTIFIKAT_POSLOVNICA1`
    FOREIGN KEY (`idPoslovnica`)
    REFERENCES `POSLOVNICA` (`idPoslovnica`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_SERTIFIKAT_SLIKA1`
    FOREIGN KEY (`idSlika`)
    REFERENCES `SLIKA` (`idSlika`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_SERTIFIKAT_ZAPOSLENI1`
    FOREIGN KEY (`idZaposleni`)
    REFERENCES `ZAPOSLENI` (`idZaposleni`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SLIKA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SLIKA` (
  `Naziv` VARCHAR(50) NOT NULL,
  `idAutor` INT NOT NULL,
  `idSlika` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`idSlika`),
  INDEX `fk_Slika_Autor_idx` (`idAutor` ASC) VISIBLE,
  INDEX `fk_SLIKA_PROIZVOD1_idx` (`idSlika` ASC) VISIBLE,
  UNIQUE INDEX `idSlika_UNIQUE` (`idSlika` ASC) VISIBLE,
  CONSTRAINT `fk_Slika_Autor`
    FOREIGN KEY (`idAutor`)
    REFERENCES `AUTOR` (`idAutor`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `fk_SLIKA_PROIZVOD1`
    FOREIGN KEY (`idSlika`)
    REFERENCES `PROIZVOD` (`idProizvod`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `STATUS_NARUDZBE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `STATUS_NARUDZBE` (
  `idStatusNarudzbe` INT NOT NULL AUTO_INCREMENT,
  `Naziv_statusa` VARCHAR(20) NULL,
  PRIMARY KEY (`idStatusNarudzbe`),
  UNIQUE INDEX `idSTATUS_NARUDZBE_UNIQUE` (`idStatusNarudzbe` ASC) VISIBLE,
  UNIQUE INDEX `Naziv_statusa_UNIQUE` (`Naziv_statusa` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `USTANOVA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `USTANOVA` (
  `Ime` VARCHAR(80) NOT NULL,
  `idKlijent` INT NOT NULL,
  PRIMARY KEY (`idKlijent`),
  INDEX `fk_Ustanova_Klijent1_idx` (`idKlijent` ASC) VISIBLE,
  UNIQUE INDEX `idKlijent_UNIQUE` (`idKlijent` ASC) VISIBLE,
  CONSTRAINT `fk_Ustanova_Klijent1`
    FOREIGN KEY (`idKlijent`)
    REFERENCES `KLIJENT` (`idKlijent`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ZAPOSLENI`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ZAPOSLENI` (
  `idZaposleni` INT NOT NULL AUTO_INCREMENT,
  `Ime` VARCHAR(25) NOT NULL,
  `Prezime` VARCHAR(30) NOT NULL,
  `brojTelefona` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`idZaposleni`),
  UNIQUE INDEX `idZaposleni_UNIQUE` (`idZaposleni` ASC) VISIBLE,
  UNIQUE INDEX `brojTelefona_UNIQUE` (`brojTelefona` ASC) VISIBLE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
